# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48c21c9d3acc06116943556eb33bfd1c5ce3b252537aa8cd11a54e7077030db22987b600f5b86593836059a319fb55f28c2ea33b4964989cb939fef6c582f8a8

test:
  secret_key_base: 628f105843f52a8287c8a53d44ff59abeb091cd26d9f3df879565590145bdc3b8198309a83dc21ce44362030c669e3dc8f166fd1343e2771196d6566a3b8c608

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
